/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

object Config {

    object Versions {
        const val http4k = "3.107.0"
        const val kotlin = "1.3.20"
        const val kitteh = "5.0.1"
    }

    object Plugins {
        const val kotlin_jvm = "org.jetbrains.kotlin.jvm"
    }

    object Libs {
        const val http4k_client_ws = "org.http4k:http4k-client-websocket:${Config.Versions.http4k}"
        const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${Config.Versions.kotlin}"
        const val kitteh = "org.kitteh.irc:client-lib:${Config.Versions.kitteh}"
    }

    object TestLibs {
        const val kotlin_test = "org.jetbrains.kotlin:kotlin-test"
        const val kotlin_test_junit = "org.jetbrains.kotlin:kotlin-test-junit"
    }
}

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.11")

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven { url = uri("https://maven.ci.carrot.codes") }
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation(Config.Libs.kotlin)

    // http4k Websockets
    implementation(Config.Libs.http4k_client_ws)

    // Kitteh
    implementation(Config.Libs.kitteh)

    // Use the Kotlin test library.
    testImplementation(Config.TestLibs.kotlin_test)

    // Use the Kotlin JUnit integration.
    testImplementation(Config.TestLibs.kotlin_test_junit)
}

application {
    // Define the main class for the application.
    mainClassName = "twitchbot.AppKt"
}

tasks {
    compileKotlin {
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }
}
